import io
import tempfile
import unittest
from pathlib import Path

from check_int_coverage import check


class IntegrationCoverageTests(unittest.TestCase):
    def setUp(self):
        temporary = tempfile.TemporaryDirectory()
        self.addCleanup(temporary.cleanup)
        self.root = Path(temporary.name)
        (self.root / "go.mod").write_text("module example/app\n")
        (self.root / "main.go").write_text("package main\n")
        (self.root / "generated.go").write_text("// Code generated by tool. DO NOT EDIT.\npackage main\n")
        self.destination = self.root / "coverage.txt"
        self.output = io.StringIO()

    def check(self, entries):
        return check("mode: atomic\n" + entries, self.root, self.destination, self.output)

    def test_generated_code_is_excluded_and_unexecuted_code_counts(self):
        self.assertTrue(self.check("example/app/main.go:1.1,2.1 91 1\n"
                                   "example/app/main.go:3.1,4.1 9 0\n"
                                   "example/app/generated.go:1.1,2.1 999 0\n"))
        self.assertNotIn("generated.go", self.destination.read_text())
        self.assertIn("91.00% (91/100)", self.output.getvalue())

    def test_aggregate_is_statement_weighted_and_reports_each_package(self):
        (self.root / "small").mkdir()
        (self.root / "small" / "code.go").write_text("package small\n")
        self.assertTrue(self.check("example/app/main.go:1.1,2.1 99 1\n"
                                   "example/app/small/code.go:1.1,2.1 1 0\n"))
        self.assertIn("example/app/small: 0.00%", self.output.getvalue())
        self.assertIn("99.00% (99/100)", self.output.getvalue())

    def test_swag_generated_header_is_excluded(self):
        (self.root / "generated.go").write_text("// Package docs Code generated by swaggo/swag. DO NOT EDIT\npackage docs\n")
        self.assertTrue(self.check("example/app/main.go:1.1,2.1 1 1\n"
                                   "example/app/generated.go:1.1,2.1 999 0\n"))
        self.assertNotIn("generated.go", self.destination.read_text())

    def test_strict_unrounded_threshold(self):
        for covered, total, expected in [(89, 100, False), (90, 100, False),
                                         (91, 100, True), (90001, 100000, True)]:
            with self.subTest(covered=covered, total=total):
                self.assertEqual(expected, self.check(f"example/app/main.go:1.1,2.1 {covered} 1\n"
                                                     f"example/app/main.go:3.1,4.1 {total-covered} 0\n"))

    def test_missing_malformed_or_excluded_only_data_fails(self):
        for entries in ["", "invalid\n", "example/app/generated.go:1.1,2.1 1 1\n",
                        "example/app/main.go:1.1,2.1 -1 1\n"]:
            with self.subTest(entries=entries), self.assertRaises(ValueError):
                self.check(entries)

    def test_unexpected_dependencies_and_unsafe_paths_fail(self):
        for filename in ["dependency/code.go", "example/app/../main.go", "example/app//main.go",
                         "example/app/main.txt"]:
            with self.subTest(filename=filename), self.assertRaises(ValueError):
                self.check(f"{filename}:1.1,2.1 1 1\n")

    def test_test_sources_and_missing_files_fail(self):
        (self.root / "main_test.go").write_text("package main\n")
        with self.assertRaises(ValueError):
            self.check("example/app/main_test.go:1.1,2.1 1 1\n")
        with self.assertRaises(OSError):
            self.check("example/app/missing.go:1.1,2.1 1 1\n")

    def test_missing_module_fails(self):
        (self.root / "go.mod").write_text("go 1.26\n")
        with self.assertRaises(ValueError):
            self.check("example/app/main.go:1.1,2.1 1 1\n")
