import io
import contextlib
import tempfile
import unittest
from pathlib import Path
from unittest.mock import patch

from check_coverage import check, main, package_coverage


class CoverageTests(unittest.TestCase):
    def test_cross_package_execution_is_merged(self):
        profile = "mode: atomic\napp/a.go:1.1,2.1 5 0\napp/a.go:1.1,2.1 5 1\n"
        self.assertEqual({"app": [5, 5]}, package_coverage(profile))
        self.assertTrue(check(profile, io.StringIO()))

    def test_large_package_cannot_hide_small_package(self):
        profile = "mode: count\nbig/a.go:1.1,2.1 1000 1\nsmall/a.go:1.1,2.1 1 0\n"
        self.assertFalse(check(profile, io.StringIO()))

    def test_strict_threshold_uses_unrounded_counts(self):
        for covered, expected in [(95, False), (96, True)]:
            profile = f"mode: atomic\napp/a.go:1.1,2.1 {covered} 1\napp/b.go:1.1,2.1 {100-covered} 0\n"
            self.assertEqual(expected, check(profile, io.StringIO()))

    def test_invalid_profiles_fail_closed(self):
        for profile in ["", "mode: atomic\n", "mode: unknown\n", "mode: atomic\ninvalid\n", "mode: atomic\napp/a.go:1.1,2.1 -1 0\n", "mode: atomic\napp/a.go:1.1,2.1 1 0\napp/a.go:1.1,2.1 2 1\n"]:
            with self.subTest(profile=profile), self.assertRaises(ValueError):
                package_coverage(profile)


class UnitCoverageCommandTests(unittest.TestCase):
    def setUp(self):
        temporary = tempfile.TemporaryDirectory()
        self.addCleanup(temporary.cleanup)
        self.root = Path(temporary.name)
        (self.root / "go.mod").write_text("module example\n")
        (self.root / "code.go").write_text("package app\n")
        (self.root / "generated.go").write_text("// Code generated by tool. DO NOT EDIT.\npackage app\n")
        self.default = self.root / "default.txt"
        self.tagged = self.root / "migrate.txt"

    def run_check(self, *paths):
        with patch("check_coverage.__file__", str(self.root / "scripts/check_coverage.py")), \
                patch("sys.argv", ["check_coverage.py", *map(str, paths)]), \
                contextlib.redirect_stdout(io.StringIO()), contextlib.redirect_stderr(io.StringIO()):
            return main()

    def test_each_build_must_pass_independently(self):
        for failing, passing in [(self.default, self.tagged), (self.tagged, self.default)]:
            failing.write_text("mode: atomic\nexample/code.go:1.1,2.1 95 1\nexample/code.go:3.1,4.1 5 0\n")
            passing.write_text("mode: atomic\nexample/code.go:1.1,2.1 1000 1\n")
            self.assertEqual(1, self.run_check(self.default, self.tagged))

    def test_generated_code_is_excluded_from_unit_reports(self):
        self.default.write_text("mode: atomic\nexample/code.go:1.1,2.1 1 1\n"
                                "example/generated.go:1.1,2.1 999 0\n")
        self.assertEqual(0, self.run_check(self.default))
        self.assertNotIn("generated.go", self.default.read_text())

    def test_missing_or_invalid_build_profile_fails(self):
        self.default.write_text("mode: atomic\nexample/code.go:1.1,2.1 1 1\n")
        self.assertEqual(1, self.run_check())
        self.assertEqual(1, self.run_check(self.default, self.tagged))
        self.tagged.write_text("mode: atomic\n")
        self.assertEqual(1, self.run_check(self.default, self.tagged))
